### ISSUE TITLE
Error in install_apps.sh

### ISSUE THREAD

**Issue by Toufik-DEI** [candrist/mmdvm-image#2]
Hi,

I have some errors when do  /home/pi/Scripts/install_apps.sh related to opendv, dir missing ...

**Comment by candrist** [comment]
Thanks for reporting the errors. I really appreciate it.

What is the exact message?

The command it should be running is:

sudo chmod -R 0777 /home/opendv

This command is also in cleanup.sh.

If you run cleanup.sh when you are done you can ignore this error.

**Comment by Toufik-DEI** [comment]
Hi,
It's OK now, maybe a time and date issue on my RPI2
MMDVMHost seems not to start at reboot, I activate Background service START but MMDVMHost seems to be OFF. I need to do Background service RESTART.

Not tested if DSTAR is OK at boot, need to test that.

Maybe you can add script to turn OFF BT on RPI3 and add also YSFClients and gateway.

73's
Toufik, F0DEI

**Comment by candrist** [comment]
Because of all of the issue with IRCDDBGateway I have removed it from my image going forward.
