### ISSUE TITLE
MMDVM and IRCDDBGATEWAY not auto starting

### ISSUE THREAD

**Issue by g7kbr67** [candrist/mmdvm-image#3]
Hi Chris 

Running the latest combined mmdvm with ircddbgateway image.  Notice that mmdvm and ircddbgateway doesn't auto-start after power-up.  Have to run from GUI interface both systems.

Once running all is ok but as this is going to a remote site auto starts for both would be great.

Regards

Paul
G7KBR

**Comment by candrist** [comment]
Because of all of the issue with IRCDDBGateway I have removed it from my image going forward.
